_format_version: "1.1"

services:
- name: cat-hr-webui
  url: http://cat-hr-webui:80
  routes:
  - name: ui-root
    protocols:
    - https
    https_redirect_status_code: 307
    paths:
    - /
- name: search-orchestrator
  url: http://search-orchestrator:3001/search/api
  routes:
  - name: search-orchestrator-root
    protocols:
    - https
    https_redirect_status_code: 307
    paths:
    - /search/api
- name: keycloak
  url: https://keycloak:8443/auth
  routes:
  - name: auth
    protocols:
    - https
    paths:
    - /auth